# This file lists all the engines available to be run for analysis.
#
# Each engine must have an `image` and `description`. The value in `image` will
# be passed to `docker run` and so may be any value appropriate for that
# (repo/name:tag, image id, etc).
#
# When a repo has files that match the `enable_regexps`, that engine will be
# enabled by default in the codeclimate.yml file. That file will also have in it
# the `default_ratings_paths` globs, which are used during analysis to determine
# which files should be rated.
#
rubocop:
  image: codeclimate/codeclimate-rubocop
  description: A Ruby static code analyzer, based on the community Ruby style guide.
  community: false
  upgrade_languages:
   - Ruby
  enable_regexps:
    - \.rb$
  default_ratings_paths:
    - "**.rb"
gofmt:
  image: codeclimate/codeclimate-gofmt
  description: gofmt
  community: true
  enable_regexps:
    - \.go$
  default_ratings_paths:
    - "**.go"
golint:
  image: codeclimate/codeclimate-golint
  description: golint
  community: true
  enable_regexps:
    - \.go$
  default_ratings_paths:
    - "**.go"
govet:
  image: codeclimate/codeclimate-govet
  description: govet
  community: true
  enable_regexps:
    - \.go$
  default_ratings_paths:
    - "**.go"
coffeelint:
  image: codeclimate/codeclimate-coffeelint
  description: A style checker for CoffeeScript
  community: false
  enable_regexps:
    - \.coffee$
  default_ratings_paths:
    - "**.coffee"
eslint:
  image: codeclimate/codeclimate-eslint
  description: A JavaScript/JSX linting utility
  community: false
  upgrade_languages:
    - JavaScript
  enable_regexps:
    - \.js$
    - \.jsx$
  default_ratings_paths:
    - "**.js"
    - "**.jsx"
csslint:
  image: codeclimate/codeclimate-csslint
  description: Automated linting of Cascading Stylesheets
  community: false
  enable_regexps:
    - \.css$
  default_ratings_paths:
    - "**.css"
watson:
  image: codeclimate/codeclimate-watson
  description: A young Ember Doctor to help you fix your code.
  community: true
  enable_regexps:
  default_ratings_paths:
    - "app/**"
rubymotion:
  image: codeclimate/codeclimate-rubymotion
  description: Rubymotion-specific rubocop checks
  community: true
  enable_regexps:
  default_ratings_paths:
    - "**.rb"
bundler-audit:
  image: codeclimate/codeclimate-bundler-audit
  description: Patch-level verification for Bundler
  community: false
  upgrade_languages:
    - Ruby
  enable_regexps:
    - Gemfile\.lock
  default_ratings_paths:
    - Gemfile.lock
phpcodesniffer:
  image: codeclimate/codeclimate-phpcodesniffer
  description: PHP Code Sniffer
  community: false
  upgrade_languages:
    - PHP
  enable_regexps:
    - \.php$
    - \.module$
    - \.inc$
  default_ratings_paths:
    - "**.php"
    - "**.module"
    - "**.inc"
phpmd:
  image: codeclimate/codeclimate-phpmd
  description: PHP Mess Detector
  community: false
  upgrade_languages:
    - PHP
  enable_regexps:
    - \.php$
    - \.module$
    - \.inc$
  default_ratings_paths:
    - "**.php"
    - "**.module"
    - "**.inc"
fixme:
  image: codeclimate/codeclimate-fixme
  description: Find FIXME, TODO, HACK, etc. comments
  community: false
  enable_regexps:
  default_ratings_paths:
foodcritic:
  image: codeclimate/codeclimate-foodcritic
  description: Lint tool for Chef cookbooks
  community: true
  enable_regexps:
  default_ratings_paths:
scss-lint:
  image: codeclimate/codeclimate-scss-lint
  description: Configurable tool for writing clean and consistent SCSS
  community: true
  enable_regexps:
  default_ratings_paths:
    - "**.scss"
requiresafe:
  image: codeclimate/codeclimate-requiresafe
  description: Security tool for Node.js dependencies
  community: true
  enable_regexps:
  default_ratings_paths:
