# This file lists all the engines available to be run for analysis.
#
# Each engine must have `channels` (with a `stable` key) and `description`. The
# values in `channels` will be passed to `docker run` and so may be any value
# appropriate for that (repo/name:tag, image id, etc).
#
# If engines have `auto_enable_paths`, the presence of any of these files will
# automatically enable that plugin and run it with { config: { file: PATH } }.
#
apexmetrics:
  channels:
    stable: codeclimate/codeclimate-apexmetrics
  description: ApexMetrics is a static code analysis tool for Salesforce.com Apex.
brakeman:
  channels:
    stable: codeclimate/codeclimate-brakeman
  description: Static analysis tool which checks Ruby on Rails applications for security vulnerabilities.
bundler-audit:
  channels:
    stable: codeclimate/codeclimate-bundler-audit
  description: Patch-level verification for Bundler.
checks:
  channels:
    beta: codeclimate/codeclimate-checks:beta
  description: Maintainability and reliability checks for PHP, Python, JS, and more.
  default_config:
    languages:
      - javascript
      - python
      - php
checkstyle:
  channels:
    beta: codeclimate/codeclimate-checkstyle:beta
  description: Helps programmers write Java that adheres to a coding standard.
complexity-ruby:
  channels:
    beta: codeclimate/codeclimate-complexity-ruby:b47
  description: Code Climate Complexity Checks for Ruby
  default_config:
    languages:
      - ruby
csslint:
  auto_enable_paths:
  - .csslintrc
  channels:
    stable: codeclimate/codeclimate-csslint
  description: Automated linting of Cascading Stylesheets.
coffeelint:
  auto_enable_paths:
  - coffeelint.json
  channels:
    stable: codeclimate/codeclimate-coffeelint
  description: A style checker for CoffeeScript.
codescan:
  channels:
    beta: codeclimate/codeclimate-codescan:beta
  description: >
    A static analysis tool for Salesforce.com Apex, Visual Force, Aura and
    Lightning.
credo:
  channels:
    beta: codeclimate/codeclimate-credo:beta
  description: >
    A static code analysis tool for the Elixir language with a focus on code
    consistency and teaching.
duplication:
  channels:
    beta: codeclimate/codeclimate-duplication:beta
    cronopio: codeclimate/codeclimate-duplication:cronopio
    stable: codeclimate/codeclimate-duplication
  description: Structural duplication detection for Ruby, Python, JavaScript, and PHP.
  default_config:
    languages:
      - ruby
      - javascript
      - python
      - php
eslint:
  auto_enable_paths:
  - .eslintrc
  - .eslintrc.js
  - .eslintrc.json
  - .eslintrc.yaml
  - .eslintrc.yml
  channels:
    stable: codeclimate/codeclimate-eslint
    eslint-1: codeclimate/codeclimate-eslint:eslint-1
    eslint-2: codeclimate/codeclimate-eslint:eslint-2
    eslint-3: codeclimate/codeclimate-eslint:eslint-3
  description: A JavaScript/JSX linting utility.
flog:
  channels:
    beta: codeclimate/codeclimate-flog:beta
    stable: codeclimate/codeclimate-flog
  description: Easy to read reporting of complexity/pain for Ruby code.
  default_config:
    all: false
    threshold: 0.6
gofmt:
  channels:
    stable: codeclimate/codeclimate-gofmt
  description: Checks the formatting of Go programs.
golint:
  channels:
    stable: codeclimate/codeclimate-golint
  description: A linter for Go.
govet:
  channels:
    stable: codeclimate/codeclimate-govet
  description: Reports suspicious constructs in Go programs.
grep:
  channels:
    beta: codeclimate/codeclimate-grep
    stable: codeclimate/codeclimate-grep
  description: Detects specified patterns in files
fixme:
  channels:
    stable: codeclimate/codeclimate-fixme
  description: Finds FIXME, TODO, HACK, etc. comments.
foodcritic:
  channels:
    stable: codeclimate/codeclimate-foodcritic
  description: Lint tool for Chef cookbooks.
gnu-complexity:
  channels:
    stable: codeclimate/codeclimate-gnu-complexity
  description: Checks complexity of C code
haxe-checkstyle:
  channels:
    stable: codeclimate/codeclimate-haxe-checkstyle
  description: Checkstyle is a development library to help developers write Haxe code that adheres to a coding standard.
haml-lint:
  channels:
    beta: codeclimate/codeclimate-haml-lint:beta
  description: Tool for writing clean and consistent HAML.
hlint:
  channels:
    stable: codeclimate/codeclimate-hlint
  description: Linter for Haskell programs.
kibit:
  channels:
    stable: codeclimate/codeclimate-kibit
  description: Static code analyzer for Clojure, ClojureScript, cljx and other Clojure variants.
markdownlint:
  channels:
    stable: codeclimate/codeclimate-markdownlint
  description: Flags style issues within Markdown files.
nodesecurity:
  channels:
    stable: codeclimate/codeclimate-nodesecurity
  description: Security tool for Node.js dependencies.
pep8:
  channels:
    stable: codeclimate/codeclimate-pep8
  description: Static analysis tool to check Python code against the style conventions outlined in PEP-8.
phan:
  channels:
    stable: codeclimate/codeclimate-phan
  description: Phan is a static analyzer for PHP.
phpcodesniffer:
  channels:
    stable: codeclimate/codeclimate-phpcodesniffer
  description: Detects violations of a defined set of coding standards in PHP.
phpmd:
  channels:
    stable: codeclimate/codeclimate-phpmd
  description: A PHP static analysis tool.
proselint:
  channels:
    beta: codeclimate/codeclimate-proselint:beta
  description: A linter for prose.
pmd:
  channels:
    beta: codeclimate/codeclimate-pmd:beta
  description: Source code analyzer for Java.
radon:
  channels:
    stable: codeclimate/codeclimate-radon
  description: Python tool used to compute Cyclomatic Complexity.
reek:
  channels:
    stable: codeclimate/codeclimate-reek
  description: "Reek examines Ruby classes, modules, and methods and reports any code smells it finds."
requiresafe:
  channels:
    stable: codeclimate/codeclimate-nodesecurity
  description: Security tool for Node.js dependencies.
rubocop:
  auto_enable_paths:
  - .rubocop.yml
  channels:
    stable: codeclimate/codeclimate-rubocop
    cache-support: codeclimate/codeclimate-rubocop:cache-support
rubocop-v35:
  channels:
    stable: codeclimate/codeclimate-rubocop:v35
rubymotion:
  channels:
    stable: codeclimate/codeclimate-rubymotion
  description: Rubymotion-specific rubocop checks.
rustfmt:
  channels:
    beta: codeclimate/codeclimate-rustfmt:beta
  description: A tool for formatting Rust code according to style guidelines.
scss-lint:
  channels:
    stable: codeclimate/codeclimate-scss-lint
  description: Configurable tool for writing clean and consistent SCSS.
shellcheck:
  channels:
    stable: codeclimate/codeclimate-shellcheck
  description: A static analysis tool for shell scripts.
stylelint:
  channels:
    beta: codeclimate/codeclimate-stylelint:beta
    stable: codeclimate/codeclimate-stylelint
  description: A mighty, modern CSS linter
tailor:
  channels:
    stable: codeclimate/codeclimate-tailor
  description: Cross-platform static analyzer and linter for Swift.
tslint:
  channels:
    beta: codeclimate/codeclimate-tslint:beta
  description: An extensible linter for the TypeScript language
watson:
  channels:
    stable: codeclimate/codeclimate-watson
  description: A young Ember Doctor to help you fix your code.
vint:
  channels:
    stable: codeclimate/codeclimate-vint
  description: Fast and Highly Extensible Vim script Language Lint implemented by Python.
