# This file lists all the engines available to be run for analysis.
#
# Each engine must have `channels` (with a `stable` key) and `description`. The
# values in `channels` will be passed to `docker run` and so may be any value
# appropriate for that (repo/name:tag, image id, etc).
apexmetrics:
  channels:
    stable: codeclimate/codeclimate-apexmetrics
  description: ApexMetrics is a static code analysis tool for Salesforce.com Apex.
bandit:
  channels:
    stable: codeclimate/codeclimate-bandit
  description: A tool designed to find common security issues in Python code.
brakeman:
  channels:
    stable: codeclimate/codeclimate-brakeman
  description: A static analysis tool which checks Ruby on Rails applications for security vulnerabilities.
bundler-audit:
  channels:
    stable: codeclimate/codeclimate-bundler-audit
  description: Patch-level verification for Bundler.
checkstyle:
  channels:
    stable: codeclimate/codeclimate-checkstyle
  description: Helps programmers write Java that adheres to a coding standard.
csslint:
  channels:
    stable: codeclimate/codeclimate-csslint
  description: Automated linting of Cascading Stylesheets.
coffeelint:
  channels:
    stable: codeclimate/codeclimate-coffeelint
  description: A style checker for CoffeeScript.
codenarc:
  channels:
    stable: codeclimate/codeclimate-codenarc
  description: >
    CodeNarc analyzes Groovy code for defects, bad practices, inconsistencies,
    style issues, and more.
cppcheck:
  channels:
    stable: codeclimate/codeclimate-cppcheck
  description: >
    Cppcheck is a static analysis tool for C/C++ code.
credo:
  channels:
    stable: codeclimate/codeclimate-credo
  description: >
    A static code analysis tool for the Elixir language with a focus on code
    consistency and teaching.
duplication:
  channels:
    stable: codeclimate/codeclimate-duplication
  description: Structural duplication detection for Ruby, Python, Java, JavaScript, and PHP.
editorconfig:
  channels:
    stable: codeclimate/codeclimate-editorconfig
  description: >
    EditorConfig helps developers define and maintain consistent coding styles
    between different editors and IDEs.
ember-template-lint:
  channels:
    stable: codeclimate/codeclimate-ember-template-lint
  description: Linter for Ember or Handlebars templates.
eslint:
  channels:
    stable: codeclimate/codeclimate-eslint
    eslint-1: codeclimate/codeclimate-eslint:eslint-1
    eslint-2: codeclimate/codeclimate-eslint:eslint-2
    eslint-3: codeclimate/codeclimate-eslint:eslint-3
    eslint-4: codeclimate/codeclimate-eslint:eslint-4
    eslint-5: codeclimate/codeclimate-eslint:eslint-5
    eslint-6: codeclimate/codeclimate-eslint:eslint-6
  description: A JavaScript/JSX linting utility.
flog:
  channels:
    stable: codeclimate/codeclimate-flog
  description: Easy to read reporting of complexity/pain for Ruby code.
git-legal:
  channels:
    stable: codeclimate/codeclimate-git-legal
  description: License compliance and compatibility analysis.
gofmt:
  channels:
    stable: codeclimate/codeclimate-gofmt
  description: Checks the formatting of Go programs.
golint:
  channels:
    stable: codeclimate/codeclimate-golint
  description: A linter for Go.
govet:
  channels:
    stable: codeclimate/codeclimate-govet
  description: Reports suspicious constructs in Go programs.
grep:
  channels:
    stable: codeclimate/codeclimate-grep
  description: Detects specified patterns in files.
fixme:
  channels:
    stable: codeclimate/codeclimate-fixme
  description: Finds FIXME, TODO, HACK, etc. comments.
foodcritic:
  channels:
    stable: codeclimate/codeclimate-foodcritic
  description: Lint tool for Chef cookbooks.
git-legal:
  channels:
    stable: codeclimate/codeclimate-git-legal
  description: License compliance and compatibility analysis.
gnu-complexity:
  channels:
    stable: codeclimate/codeclimate-gnu-complexity
  description: Checks complexity of C code.
haxe-checkstyle:
  channels:
    stable: codeclimate/codeclimate-haxe-checkstyle
  description: Checkstyle is a development library to help developers write Haxe code that adheres to a coding standard.
haml-lint:
  channels:
    stable: codeclimate/codeclimate-haml-lint
  description: A tool for writing clean and consistent HAML.
hlint:
  channels:
    stable: codeclimate/codeclimate-hlint
  description: A linter for Haskell programs.
kibit:
  channels:
    stable: codeclimate/codeclimate-kibit
  description: Static code analyzer for Clojure, ClojureScript, cljx and other Clojure variants.
luacheck:
  channels:
    stable: codeclimate/codeclimate-luacheck
  description: >
    A tool for linting and static analysis of Lua code.
markdownlint:
  channels:
    stable: codeclimate/codeclimate-markdownlint
  description: Flags style issues within Markdown files.
nodesecurity:
  channels:
    stable: codeclimate/codeclimate-nodesecurity
  description: Security tool for Node.js dependencies.
pep8:
  channels:
    stable: codeclimate/codeclimate-pep8
  description: Static analysis tool to check Python code against the style conventions outlined in PEP-8.
phan:
  channels:
    stable: codeclimate/codeclimate-phan
  description: Phan is a static analyzer for PHP.
phpcodesniffer:
  channels:
    stable: codeclimate/codeclimate-phpcodesniffer
  description: Detects violations of a defined set of coding standards in PHP.
phpmd:
  channels:
    stable: codeclimate/codeclimate-phpmd
  description: A PHP static analysis tool.
pmd:
  channels:
    stable: codeclimate/codeclimate-pmd
  description: A source code analyzer for Java.
pylint:
  channels:
   beta: codeclimate/codeclimate-pylint:beta
   stable: codeclimate/codeclimate-pylint
  description: A linter for Python.
radon:
  channels:
    stable: codeclimate/codeclimate-radon
  description: Python tool used to compute Cyclomatic Complexity.
reek:
  channels:
    stable: codeclimate/codeclimate-reek
    beta: codeclimate/codeclimate-reek:beta
  description: >
    Reek examines Ruby classes, modules, and methods and reports any code
    smells it finds.
requiresafe:
  channels:
    stable: codeclimate/codeclimate-nodesecurity
  description: Security tool for Node.js dependencies.
rubocop:
  channels:
    stable: codeclimate/codeclimate-rubocop
    cache-support: codeclimate/codeclimate-rubocop:cache-support
    rubocop-0-42: codeclimate/codeclimate-rubocop:rubocop-0-42
    rubocop-0-46: codeclimate/codeclimate-rubocop:rubocop-0-46
    rubocop-0-48: codeclimate/codeclimate-rubocop:rubocop-0-48
    rubocop-0-49: codeclimate/codeclimate-rubocop:rubocop-0-49
    rubocop-0-50: codeclimate/codeclimate-rubocop:rubocop-0-50
    rubocop-0-51: codeclimate/codeclimate-rubocop:rubocop-0-51
    rubocop-0-52: codeclimate/codeclimate-rubocop:rubocop-0-52
    rubocop-0-54: codeclimate/codeclimate-rubocop:rubocop-0-54
    rubocop-0-55: codeclimate/codeclimate-rubocop:rubocop-0-55
    rubocop-0-56: codeclimate/codeclimate-rubocop:rubocop-0-56
    rubocop-0-57: codeclimate/codeclimate-rubocop:rubocop-0-57
    rubocop-0-58: codeclimate/codeclimate-rubocop:rubocop-0-58
    rubocop-0-59: codeclimate/codeclimate-rubocop:rubocop-0-59
    rubocop-0-60: codeclimate/codeclimate-rubocop:rubocop-0-60
    rubocop-0-61: codeclimate/codeclimate-rubocop:rubocop-0-61
    rubocop-0-62: codeclimate/codeclimate-rubocop:rubocop-0-62
    rubocop-0-63: codeclimate/codeclimate-rubocop:rubocop-0-63
    rubocop-0-64: codeclimate/codeclimate-rubocop:rubocop-0-64
    rubocop-0-65: codeclimate/codeclimate-rubocop:rubocop-0-65
    rubocop-0-66: codeclimate/codeclimate-rubocop:rubocop-0-66
    rubocop-0-67: codeclimate/codeclimate-rubocop:rubocop-0-67
    rubocop-0-68: codeclimate/codeclimate-rubocop:rubocop-0-68
    rubocop-0-69: codeclimate/codeclimate-rubocop:rubocop-0-69
    rubocop-0-70: codeclimate/codeclimate-rubocop:rubocop-0-70
    rubocop-0-71: codeclimate/codeclimate-rubocop:rubocop-0-71
    rubocop-0-72: codeclimate/codeclimate-rubocop:rubocop-0-72
    rubocop-0-73: codeclimate/codeclimate-rubocop:rubocop-0-73
    rubocop-0-74: codeclimate/codeclimate-rubocop:rubocop-0-74
    rubocop-0-75: codeclimate/codeclimate-rubocop:rubocop-0-75
    rubocop-0-76: codeclimate/codeclimate-rubocop:rubocop-0-76
    rubocop-0-77: codeclimate/codeclimate-rubocop:rubocop-0-77
    rubocop-0-78: codeclimate/codeclimate-rubocop:rubocop-0-78
    rubocop-0-79: codeclimate/codeclimate-rubocop:rubocop-0-79
    rubocop-0-80: codeclimate/codeclimate-rubocop:rubocop-0-80
    rubocop-0-81: codeclimate/codeclimate-rubocop:rubocop-0-81
    rubocop-0-82: codeclimate/codeclimate-rubocop:rubocop-0-82
    rubocop-0-83: codeclimate/codeclimate-rubocop:rubocop-0-83
    rubocop-0-84: codeclimate/codeclimate-rubocop:rubocop-0-84
    rubocop-0-85: codeclimate/codeclimate-rubocop:rubocop-0-85
    rubocop-0-86: codeclimate/codeclimate-rubocop:rubocop-0-86
    rubocop-0-87: codeclimate/codeclimate-rubocop:rubocop-0-87
  description: A Ruby static code analyzer, based on the community Ruby style guide.
rubymotion:
  channels:
    stable: codeclimate/codeclimate-rubymotion
  description: Rubymotion-specific rubocop checks.
sass-lint:
  channels:
    stable: codeclimate/codeclimate-sass-lint
  description: >
    A Node-only Sass linter for both sass and scss syntax!
scalastyle:
  channels:
    stable: codeclimate/codeclimate-scalastyle
  description: >
    A tool which examines your Scala code and indicates potential problems.
scss-lint:
  channels:
    stable: codeclimate/codeclimate-scss-lint
  description: A configurable tool for writing clean and consistent SCSS.
shellcheck:
  channels:
    stable: codeclimate/codeclimate-shellcheck
  description: A static analysis tool for shell scripts.
sonar-java:
  channels:
    stable: codeclimate/codeclimate-sonar-java
    beta: codeclimate/codeclimate-sonar-java:sonar-java-5-14
    sonar-java-5-14: codeclimate/codeclimate-sonar-java:sonar-java-5-14
  description: Over 400 checks for bugs, vulnerabilities, and code smells in Java code.
  minimum_memory_limit: 2_048_000_000
sonar-php:
  channels:
    stable: codeclimate/codeclimate-sonar-php
  description: SonarLint for PHP.
  minimum_memory_limit: 2_048_000_000
sonar-python:
  channels:
    stable: codeclimate/codeclimate-sonar-python
  description: SonarLint for Python.
  minimum_memory_limit: 2_048_000_000
structure:
  channels:
    stable: codeclimate/codeclimate-structure
  description: Performs structural checks on code.
stylelint:
  channels:
    stable: codeclimate/codeclimate-stylelint
  description: A mighty, modern CSS linter.
swiftlint:
  channels:
    stable: codeclimate/codeclimate-swiftlint
  description: A tool to enforce Swift style and conventions.
tailor:
  channels:
    stable: codeclimate/codeclimate-tailor
  description: Cross-platform static analyzer and linter for Swift.
tslint:
  channels:
    stable: codeclimate/codeclimate-tslint
  description: An extensible linter for the TypeScript language
watson:
  channels:
    stable: codeclimate/codeclimate-watson
  description: A young Ember Doctor to help you fix your code.
vint:
  channels:
    stable: codeclimate/codeclimate-vint
  description: Fast and Highly Extensible Vim script Language Lint implemented by Python.
